### ISSUE TITLE
Don't change the indentation of secrets

### ISSUE THREAD

**Issue by Xcalizorz** [sniptt-official/ots#17] opened 2021-08-10 13:19 UTC
Thanks for the interesting tool!

I want to store `yaml` and `json` data exactly as they are without changes to their indentation:

```json
{
  "foo": "bar"
}
```

Indentation in `json` is not very important, but can become ugly when the `json` data is larger. 

```yaml
version: v1alpha1
metadata:
  name: secret-data
spec:
  data:
    - hello world
``` 

## Expected

The expected outcome is that I get the same data back, without change in indentations. Especially `yaml` should stay exactly the same because the syntax depends on indentation.

## Actual result

```json
{
"foo": "baar"
}
```

```yaml
version: v1alpha1
metadata:
name: secret-data
spec:
data:
- hello world
```

It might be that the fault lies in the underlying encryption package.

**Comment by slavovojacek** [comment] 2021-08-10 13:29
Hi @Xcalizorz, thanks for filing the issue.

I looked into it and it seems as though the `textarea` in which we display the decrypted secret incorrectly implements the `white-space` CSS property.

It should indeed be `pre` or `pre-wrap`.

Myself or @rickymarcon will look into fixing this shortly!

**Comment by rickymarcon** [comment] 2021-08-10 13:31
Thanks for picking this up @Xcalizorz! We'll rectify this! 🚀

**Comment by rickymarcon** [comment] 2021-08-10 17:37
@Xcalizorz this is now resolved. As @slavovojacek mentioned, the root cause was CSS in the browser. Closing for now. Let us know if you run into any other issues and thanks for the post!

**Closed by rickymarcon** 2021-08-10 17:37 UTC
Labels: bug, good first issue
